experiment:
  exp_dir: /kaggle/working/
  exp_name: resume
  seed: 0

task: named-entity-recognition

dataset:
  data_file:
    train: '/kaggle/input/vlsp2018/test_set.conll'
    valid: '/kaggle/input/vlsp2018/val_set.conll'
    test: '/kaggle/input/vlsp2018/test_set.conll'
  data_type: conll

preprocessor:
  type: sequence-labeling-preprocessor
  max_length: 150

data_collator: SequenceLabelingDataCollatorWithPadding

model:
  type: sequence-labeling-model
  embedder:
    model_name_or_path: vinai/phobert-base
  dropout: 0.1
  use_crf: true

train:
  max_epochs: 2
  dataloader:
    batch_size_per_gpu: 16
  optimizer:
    type: AdamW
    lr: 5.0e-5
    param_groups:
      - regex: crf
        lr: 5.0e-1
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 20

evaluation:
  dataloader:
    batch_size_per_gpu: 16
  metrics:
    - type: ner-metric
    - type: ner-dumper
      model_type: sequence_labeling
      dump_format: conll
